version: "3"

services:
  trojan:
    image: teddysun/trojan-go
    ports:
      - "1234:1234"
    volumes:
      - ./trojan/config:/etc/trojan-go
      - ./ssl:/ssl
    links:
      - caddy:__DOCKER_CADDY__
    depends_on:
      - caddy

  caddy:
    image: caddy
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./wwwroot:/usr/src
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./ssl:/root/.caddy/acme/acme-v02.api.letsencrypt.org/sites
